version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    restart: on-failure
#    ports:
#      - "6002:80"
#    environment:
#      - PMA_ARBITRARY=0
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#      - MYSQL_ROOT_PASSWORD=root
#      - PMA_HOST=mysql
#    depends_on:
#      - mysql
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"